version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: StripeCards-Microservice
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 5002:80
